import Lanyard from "@/components/Lanyard";
import Squares from "@/components/Squares";
import TargetCursor from "@/components/TargetCursor";
import Sidebar from "@/includes/Sidebar";
import type { Metadata } from "next";
import { Figtree, Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "@/includes/Header";

const figtreeSans = Figtree({
  variable: "--font-figtree-sans",
  subsets: ["latin"],
});

const playfairSans = Playfair_Display({
  variable: "--font-playfair-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portofolio - Faiz Muazzam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${figtreeSans.variable} ${playfairSans.variable}`}
    >
      <body className={`antialiased dark`}>
        <main className="main wrapper relative w-full overflow-x-hidden">
          <div className="fixed inset-0 z-0 h-screen">
            <Squares
              speed={0.5}
              squareSize={35}
              direction="diagonal" // up, down, left, right, diagonal
              borderColor="#ff6a00ff"
              hoverFillColor="#ff6a00ff"
            />
          </div>
          <div className="absolute inset-0 z-10">
            <div className="bg-black md:opacity-70 opacity-60 w-full h-full"></div>
          </div>
          <TargetCursor spinDuration={2} hideDefaultCursor={true} />
          <div className="block min-h-screen w-screen overflow-x-hidden relative z-20">
            <div className="absolute w-[1092px] top-0 right-0 translate-x-[30%] z-0 hidden xl:block">
              <div className="relative">
                <Lanyard position={[0, 0, 20]} gravity={[0, -40, 0]} />
              </div>
            </div>
            <Header />
            <div className="lg:flex max-w-[1320px] m-auto relative z-10">
              <div className="xl:w-[400px] lg:w-[320px] xl:pl-0 lg:pl-5">
                <Sidebar />
              </div>
              <div className="flex-1 content px-5 lg:pt-20 pt-16 max-md:pt-6">
                <div className="lg:max-w-full max-w-[540px] mx-auto">
                  {children}
                </div>
              </div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
