import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import Sidebar from "@/includes/Sidebar";
import TargetCursor from "@/components/TargetCursor";


const jostSans = Jost({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Portofolio - Faiz Muazzam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${jostSans.className} antialiased dark`}
      >
        <main className="main wrapper">
          <TargetCursor
            spinDuration={2}
            hideDefaultCursor={true}
          />
          <div className="block min-h-screen w-screen overflow-x-hidden">
            <Sidebar />
            <div className="content ml-[360px] py-32 px-4">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
